config/routes.rb
Rails.application.routes.draw do
  resources :visits
  resources :treatments
  resources :appointments
  resources :patients
  resources :physicians
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'

end

app/models/treatment.rb
class Treatment < ApplicationRecord
    has_many :visits
    has_many :appointments, :through => :visits
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.fetch(:treatment, {})
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= form_for(treatment) do |f| %>
  <% if treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Treatments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
        <td><%= link_to 'Show', treatment %></td>
        <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
        <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treatment', new_treatment_path %>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_treatment_path(@treatment) %> |
<%= link_to 'Back', treatments_path %>